package pojos;
// Generated 2021.04.22. 10:47:37 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Client generated by hbm2java
 */
@Entity
@Table(name="client"
    ,catalog="jobs"
)
public class Client  implements java.io.Serializable {


     private Integer clientId;
     private String clientName;
     private String clientEmail;

    public Client() {
    }

    public Client(String clientName, String clientEmail) {
       this.clientName = clientName;
       this.clientEmail = clientEmail;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="client_id", unique=true, nullable=false)
    public Integer getClientId() {
        return this.clientId;
    }
    
    public void setClientId(Integer clientId) {
        this.clientId = clientId;
    }

    
    @Column(name="client_name", length=100)
    public String getClientName() {
        return this.clientName;
    }
    
    public void setClientName(String clientName) {
        this.clientName = clientName;
    }

    
    @Column(name="client_email", length=100)
    public String getClientEmail() {
        return this.clientEmail;
    }
    
    public void setClientEmail(String clientEmail) {
        this.clientEmail = clientEmail;
    }




}


