package pojos;
// Generated 2021.04.22. 10:47:37 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Position generated by hbm2java
 */
@Entity
@Table(name="position"
    ,catalog="jobs"
)
public class Position  implements java.io.Serializable {


     private Integer jobId;
     private Integer clientId;
     private String jobName;
     private String jobLocation;

    public Position() {
    }

    public Position(Integer clientId, String jobName, String jobLocation) {
       this.clientId = clientId;
       this.jobName = jobName;
       this.jobLocation = jobLocation;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="job_id", unique=true, nullable=false)
    public Integer getJobId() {
        return this.jobId;
    }
    
    public void setJobId(Integer jobId) {
        this.jobId = jobId;
    }

    
    @Column(name="client_id")
    public Integer getClientId() {
        return this.clientId;
    }
    
    public void setClientId(Integer clientId) {
        this.clientId = clientId;
    }

    
    @Column(name="job_name", length=50)
    public String getJobName() {
        return this.jobName;
    }
    
    public void setJobName(String jobName) {
        this.jobName = jobName;
    }

    
    @Column(name="job_location", length=50)
    public String getJobLocation() {
        return this.jobLocation;
    }
    
    public void setJobLocation(String jobLocation) {
        this.jobLocation = jobLocation;
    }




}


